@TransmissionManager_Web_HostAddress = http://localhost:9092/api/v1/torrents

# Get a page of torrents
GET {{TransmissionManager_Web_HostAddress}}/

###

# Get a page of 5 torrents ordered by Name, which have cron specified
# and name, download dir, source uri or hash string start with "Mi"
GET {{TransmissionManager_Web_HostAddress}}/?orderBy=Name&take=5&propertyStartsWith=Mi&cronExists=True

###

# Get one torrent by id
GET {{TransmissionManager_Web_HostAddress}}/1

###

# Add a torrent by the address of its web page
# Do not provide sourceKind to default to WebPage
# Do not provide cron if you don't want the torrent to be automatically updated
# Do not provide magnetRegexPattern to use a global one
POST {{TransmissionManager_Web_HostAddress}}/
Content-Type: application/json

{
    "sourceUri": "https://nnmclub.to/forum/viewtopic.php?t=206418",
    "downloadDir": "/videos",
    "cron": "0 11,17 * * *"
}

###

# Add a torrent by the address of a JSON API that exposes its info hash
# The fragment (everything after "#") is an RFC 6901 JSON Pointer selecting the hash in the response
# The indices depend on the API's response shape - fetch it once to see where the hash sits
# magnetRegexPattern is not used by this source kind - the magnet link is built from the hash
POST {{TransmissionManager_Web_HostAddress}}/
Content-Type: application/json

{
    "sourceUri": "https://api.rutracker.cc/v1/static/pvc/f/1106#/result/6880555/7",
    "sourceKind": "JsonPointer",
    "downloadDir": "/videos",
    "cron": "0 11,17 * * *"
}

###

# Refresh a torrent by id
POST {{TransmissionManager_Web_HostAddress}}/1
Content-Type: application/json

###

# Update existing torrent's cron and magnet-finding regex (requires the current torrent version)
PATCH {{TransmissionManager_Web_HostAddress}}/1?version=1
Content-Type: application/json

{
    "magnetRegexPattern": "magnet:\\?xt=urn:[^\"]+",
    "cron": "0 10,16 * * *"
}

###

# Clear existing torrent's cron and magnet-finding regex using empty strings
PATCH {{TransmissionManager_Web_HostAddress}}/1?version=2
Content-Type: application/json

{
    "magnetRegexPattern": "",
    "cron": ""
}

###

# Remove a torrent from Transmission Manager by id (requires the current torrent version)
DELETE {{TransmissionManager_Web_HostAddress}}/1?version=3

###

# Remove a torrent from Transmission Manager by id, also remove it from Transmission and delete the data
DELETE {{TransmissionManager_Web_HostAddress}}/1?version=3&deleteType=LocalAndTransmissionAndData

###
