@TransmissionManager_Web_HostAddress = http://localhost:9092/api/v1/torrents

# Get a page of torrents
GET {{TransmissionManager_Web_HostAddress}}/

###

# Get 5 torrents ordered by ID if their ID is greater than 2, name starts with "Mi" and cron is specified
GET {{TransmissionManager_Web_HostAddress}}/?take=5&afterId=2&nameStartsWith=Mi&cronExists=true

###

# Get one torrent by id
GET {{TransmissionManager_Web_HostAddress}}/1

###

# Add a torrent by web page uri
# Do not provide cron if you don't want the torrent to be automatically updated
# Do not provide magnetRegexPattern to use a global one
POST {{TransmissionManager_Web_HostAddress}}/
Content-Type: application/json

{
    "webPageUri": "https://nnmclub.to/forum/viewtopic.php?t=206418",
    "downloadDir": "/videos",
    "cron": "0 11,17 * * *"
}

###

# Refresh a torrent by id
POST {{TransmissionManager_Web_HostAddress}}/1
Content-Type: application/json

""

###

# Update existing torrent's download directory, cron and magnet-finding regex
PATCH {{TransmissionManager_Web_HostAddress}}/1
Content-Type: application/json

{
    "downloadDir": "/tvshows",
    "magnetRegexPattern": "\\\"(?<magnet>magnet:\\?xt=urn:btih:.*?)\\\"",
    "cron": "0 10,16 * * *"
}

###

# Clear existing torrent's cron and magnet-finding regex using empty strings
PATCH {{TransmissionManager_Web_HostAddress}}/1
Content-Type: application/json

{
    "cron": "",
    "magnetRegexPattern": ""
}

###

# Remove a torrent from Transmission Manager by id
DELETE {{TransmissionManager_Web_HostAddress}}/1

###
