name: "Build and Test"

on: [push]

env:
  ConnectionStrings__AppDb: Data Source=test.db

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore src/TransmissionManager.slnx

    - name: Build solution
      run: dotnet build src/TransmissionManager.slnx --no-restore

    - name: Run all tests
      run: dotnet test src/TransmissionManager.slnx --no-build --verbosity normal

    - name: Publish API
      run: dotnet publish src/TransmissionManager.Api -c Release -o published

    - name: Start published API
      working-directory: ./published
      run: ./TransmissionManager.Api &

    - name: Wait for published API to start
      run: sleep 5

    - name: Health-check published API
      run: curl localhost:9092/api/v1/torrents
