// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TransmissionManager.Database.DbContextOptimized
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("722d1b97-270e-4549-bea8-1857ac0453f8"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var torrent = TorrentEntityType.Create(this);

            TorrentEntityType.CreateAnnotations(torrent);

            AddAnnotation("ProductVersion", "10.0.10");
        }
    }
}
