// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TransmissionManager.Database.DbContextOptimized
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3da05aa4-4234-48e5-a7d5-c9a458e9913b"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var torrent = TorrentEntityType.Create(this);

            TorrentEntityType.CreateAnnotations(torrent);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
