// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TransmissionManager.Database.DbContextOptimized;
using TransmissionManager.Database.Services;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
