// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransmissionManager.Database.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TransmissionManager.Database.DbContextOptimized
{
    [EntityFrameworkInternal]
    public partial class TorrentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TransmissionManager.Database.Models.Torrent",
                typeof(Torrent),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 6,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(Torrent).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);

            var cron = runtimeEntityType.AddProperty(
                "Cron",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("Cron", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<Cron>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var downloadDir = runtimeEntityType.AddProperty(
                "DownloadDir",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("DownloadDir", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<DownloadDir>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var hashString = runtimeEntityType.AddProperty(
                "HashString",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("HashString", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<HashString>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var magnetRegexPattern = runtimeEntityType.AddProperty(
                "MagnetRegexPattern",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("MagnetRegexPattern", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<MagnetRegexPattern>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var refreshDate = runtimeEntityType.AddProperty(
                "RefreshDate",
                typeof(DateTime),
                propertyInfo: typeof(Torrent).GetProperty("RefreshDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<RefreshDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            refreshDate.SetValueConverter(new ValueConverter<DateTime, DateTime>(
                DateTime (DateTime date) => date.ToUniversalTime(),
                DateTime (DateTime date) => DateTime.SpecifyKind(date, DateTimeKind.Utc)));
            refreshDate.SetSentinelFromProviderValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(Torrent).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);

            var webPageUri = runtimeEntityType.AddProperty(
                "WebPageUri",
                typeof(string),
                propertyInfo: typeof(Torrent).GetProperty("WebPageUri", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Torrent).GetField("<WebPageUri>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { cron });

            var index0 = runtimeEntityType.AddIndex(
                new[] { downloadDir });

            var index1 = runtimeEntityType.AddIndex(
                new[] { hashString },
                unique: true);

            var index2 = runtimeEntityType.AddIndex(
                new[] { name });

            var index3 = runtimeEntityType.AddIndex(
                new[] { refreshDate });

            var index4 = runtimeEntityType.AddIndex(
                new[] { webPageUri },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Torrents");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
